changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Added
      labels:
        - enhancement
        - feature
    - title: Fixed
      labels:
        - bug
        - fix
    - title: Other changes
      labels:
        - "*"
