minimum_pre_commit_version: "4.0.0"
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: Pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
        always_run: true
